spring.application.name=praesens

spring.datasource.url=jdbc:h2:file:./data/praesensdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

openweather.api.key=b280c996f8f65acd18b0a225c48fcdb5
openweather.api.url=https://api.openweathermap.org/data/2.5/weather

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true